name: Build and deploy Next.js to Azure
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
permissions:
  contents: read
  id-token: write
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
 
      - name: Install dependencies and build
        run: |
          cd .
          npm install
          npm run build
          # Copy node_modules inside standalone folder so container can find dependencies
          cp -R .next/standalone/* .
        shell: bash
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

 
      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F9E37486A82402E93199A5EA74913CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4C91BE4D19E24136947DFB2F560FD36C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E453C9D894F14427A012D64EAB94A48B }}
 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NEXT-FRONTEND-TEST'
          slot-name: 'Production'
          package: .